sudo: required
services:
  - docker

before_install:
  - docker build -t docker-react -f Dockerfile.dev .

script:
  - docker run docker-react npm run test
deploy:
  provider: elasticbeanstalk
  region: 'us-east-2'
  app: 'docker-react'
  env: 'Dockerreact-env'
  bucket_name: 'elasticbeanstalk-us-east-2-757943668377'
  # bucket_path: 'docker-react'
  on:
    branch: master
  access_key_id:
    secure: 'AKIA3A6HWR2M2O2WZ3WO'
  secret_access_key:
    secure: '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'
